### PR TITLE
add base testcases

### PR DESCRIPTION
**Pull request by TheRealHaoLiu**
For a selected managed cluster must be able to enable managed-serviceaccount addon
- Validate the deployment of addon
For a selected managed cluster must be able to create managed-serviceaccount
- Validate the creation of serviceaccount (on managedcluster)
- Validate the creation of serviceaccount token secret on hub
- Validate the validity of the serviceaccount token by comparing to the serviceaccount token on managedcluster

TODO:
Must be able to enable the managed-serviceaccount feature
- validate the enablement
pending MCE/ACM inclusion of managed-serviceaccount feature

### CODE REVIEW

**Comment by TheRealHaoLiu** [comment]
https://github.com/stolostron/backlog/issues/19256

**Review by hanqiuzh — APPROVED** [review]

**Comment by TheRealHaoLiu** [comment]
this PR is on hold till managed-serviceaccount is integrated into ACM and MCE

**Pull request merged**
